LSSTScienceCollaborations/StackClub

- notebooks/Hello_World.ipynb
@kadrlica Here's an example tutorial notebook, for teaching Stack Club members a sensible git/GitHub workflow. I made this in and pushed it from the jupyterlabdemo :-) See what you think!
This is in response to #11
> First notebook, edited at and pushed from jupyterlab

- notebooks/Hello_World.ipynb
Thanks Alex! I can merge this straight away I think :-)
> Adding Alex's mark-up to Hello World notebook

- notebooks/Hello_World.ipynb
> Switched Hello World to http cloning

- notebooks/Hello_World.ipynb
I made my first commit to the Hello World notebook - ready for code review, @drphilmarshall
> Greg's changes to "Hello World"

- GettingStarted.md
Needs checking and extending, but the Getting Started notes now have a section on data access on the LSP system. Not yet ready to merge, the paths are still uncertain.
> Notes on data access

- GettingStarted/Hello_World.ipynb
I'm following instructions and submitting a pull request, since I suspect future users will indeed submit pull requests against their test branches where they've edited this Notebook.
Suggestions that I didn't include as edits in the Notebook:
Under "3. Pushing Your Commits", you may note that users could be asked for their GitHub credentials. I use keys and had to look up my password! They may also need to set the git user configuration info (email and name) when they first commit (in part 2.).
Under "3. Pushing Your Commits", you may remind the user that the "git push origin [branch name]" should be passed the same branch name that was created in "2. Committing Your Changes". Someone new to git may follow the example verbatim, which switches between examples by Phil and Greg.
> Test pull request for Hello_World.ipynb, with minor suggestions.

- GettingStarted/GettingStarted.md
@drphilmarshall @Madejski  can someone approve this?
> Fixed typo

- GettingStarted/README.md
> Fix link to Hello World notebook in README.md

- Validation/image_quality_demo.ipynb
I addressed @jtmyles's review comments in #78 , verified the notebook on v16, and adopted SHORTCUT=True as standard. This PR shows @bechtol these changes - but in the interests of time I'm going to merge this and then the main PR. If we want to revert, this is the one commit to target.
> Patched image_quality_demo notebook

- SourceDetection/LowSurfaceBrightness.ipynb
Filtering warnings and some minor cleanup.
> Quieting LSB Notebook

- GettingStarted/HelloWorld.ipynb
Testing that editing the HelloWorld.ipynb Notebook works
> Added cell to bottom of notebook

- GettingStarted/HelloWorld.ipynb
Entered some minor changes into HelloWorld.ipynb...
> JCarlin's Hello World PR

- GettingStarted/HelloWorld.ipynb
> Qingling's request (finally)

- GettingStarted/HelloWorld.ipynb
> Editing Hello World

- GettingStarted/HelloWorld.ipynb
@Madejski I added a new method for printing Hello World, see what you think!
> Demo %%bash cell route

- GettingStarted/HelloWorld.ipynb
StackClub practice:  my first StackClub pull request.
> Added line to HelloWorld.ipynb

- Basics/DataInventory.ipynb
- Basics/Exploring_A_Data_Repo.ipynb
- stackclub/taster.py
Hey @rmorgan10 - nice work with the sky coverage plotting! I figured it was time to clean up the bottom ends of our two notebooks so we can look at them together. Because PR #159 is still live, and your work is being usefully reviewed there by @kadrlica and @SimonKrughoff , I thought I'd work in a patch branch and offer you these changes to help respond to that review. I _think_ you can merge this when _you_ are ready, without comment from Alex or Simon. Then, once you have merged this PR, my changes will appear in #159 , and then we can continue discussion of Alex's comments and overall design, there. Sound OK?
> Cleaning up, trying to write about _mapper files

- GettingStarted/CheatSheet.txt
This code is ready for review!  Could you take a look please, @Madejski ?
Here are particular items I am hoping for review:
1. The git merge steps described in the cheatsheet.
2. In general:  anything in particular missing?
Many thanks!
> A new cheatsheet for following the StackClub git workflow

- GettingStarted/templates/template_Notebook.ipynb
I edited the template notebook to be betterer in this regard, and now present the world's smallest pull request! Anyone looking for a little victory? Feel free to review and approve :-)
> Avoid grep, following tip from RHL

- Basics/afw_table_guided_tour.ipynb
added a few new methods that help users navigate large schemas. also included some clarification on distinction between schema keys and python dictionary keys, as they were interchangeably used in the previous notebook. Once this is merged in #51 can be closed
> Project/afw table/ishasan

- Basics/Calexp_guided_tour.ipynb
- Basics/DataInventory.ipynb
- Deblending/lsst_stack_deblender.ipynb
- Deblending/scarlet_tutorial.ipynb
- GettingStarted/FindingDocs.ipynb
- GettingStarted/GettingStarted.md
- GettingStarted/HelloWorld.ipynb
- GettingStarted/ImportTricks.ipynb
- GettingStarted/templates/template_Notebook.ipynb
- ImageProcessing/BrighterFatterCorrection.ipynb
- ImageProcessing/Re-RunHSC.ipynb
- Validation/image_quality_demo.ipynb
- Visualization/bokeh_holoviews_datashader.ipynb
In response to #185 . Started with the Getting Started docs, but many notebooks refer to the LSP URL so a scripted replacement is in order. Will request a review when I'm done!
> Switching to lsst-lsp-stable url

- GettingStarted/HelloWorld.ipynb
> edited HelloWorld Notebook

- GettingStarted/HelloWorld.ipynb
Not yet ready for review
I am using this branch to improve the documentation for "getting started" - but more to come!
> Improved docs for git / github 

- SourceDetection/LowSurfaceBrightness.ipynb
This is a trivial update to verify that this notebook runs on v18.0.0.
> Verify LSB notebook on v18.0.0

- Deblending/lsst_stack_deblender.ipynb
updated to LSST kernel; specified that a large lsp instance should be used.
> Tweaks to lsst deblender notebook

- Deblending/lsst_stack_deblender.ipynb
This was originally intended to be for fixing both notebooks, but things have moved on significantly and @fred3m will take care of the scarlet notebook at a later date.
> Fix stack deblender notebook

- Deblending/scarlet_tutorial.ipynb
Previous PR that failed was #231. Closes #166
> updated scarlet tutorial (second try) 

- Basics/ButlerTutorial.ipynb
Update calls to the `geom` package to work with v20.
Working toward #236.
> Update ButlerTutorial for v20

- SourceDetection/Footprints.ipynb
@ih64 this should be a clean version of your notebook updated to v20 (#236). Can you review and merge?
> Clean update of footprints to v20

- Basics/Calexp_guided_tour.ipynb
@stargaser would you be willing to review this? It should run on v20 of the stack.
Working toward #236
> Update calexp guided tour to v20

- Basics/Gen3ButlerTutorial.ipynb
Created a repo with w_2020_22, which should correspond to v20.0.0. @DouglasLeeTucker would you be able to review this?
Working toward #236
> Updating gen3 butler notebook to v20

- Basics/afw_table_guided_tour.ipynb
@ih64 here is my first pass. It would be very appreciated if you could give it a look and decide what you want to do about the cross-catalog section.
Working toward #236.
> Updating afw table guided tour to v20

- GettingStarted/GettingStarted.md
- README.md
- Rules.md
Updates to top-level Readme.md and GettingStarted.md to hopefully clarify the on-boarding process. Comments, suggestions, and direct edits are very welcome!
> Updates to documentation for onboarding

- Validation/refcat_loader_demo.ipynb
The PR provides an example of loading a reference catalog with color terms and proper motions applied.
Not yet ready for review.
> Add reference catalog loader notebook
