GettingStarted.md
Now that we've launched the docs, you can use the root URL instead of the `/v/` staging path.
=> Update URLs to nb.lsst.io

Meetings.md, README.md, Visualization/README.md
I think a link to our (new) YouTube channel (actually a playlist) on the main README, plus links in the folder READMEs where appropriate. I guess a separate page listing all the meetings might be good too.
=> Links to videos

SourceDetection/LowSurfaceBrightness.ipynb
The plate scale is appropriate for HSC. Use the WCS instead of hard-coding.
=> LowSurfaceBrightness: remove hard-coded plate scale

Basics/Calexp_guided_tour.ipynb
Respond to the very helpful comments on #57 made by @PaulPrice after the PR was merged.
* Use cleaner syntax for making cutouts
* Note that the coadd and the calexp are the same class, so they should all share the same methods.
=> Cleanup cutouts syntax on calexp guided tour

GettingStarted/GettingStarted.md
Small update to the Getting Started instructions to implement club membership application form to get an LSP account. Needs reviewing for wording and tone, please!
=> LSP accounts by club membership application only

README.md
Upgrading the READMEs to point potential new members to the application form, following the LSST 2018 PCW session. I'll merge this when I'm done, these are easy changes.
=> Application form links

SourceDetection/LowSurfaceBrightness.ipynb
This implements the suggestions in #97.
=> Updates to LSB notebook after LSST PCW 2018 session

Visualization/README.md
Add a link to the with-globular notebook that has been updated for LSST 2018.
=> Add the DM demo notebook "with-globular"

Visualization/AFW_Display_Demo.ipynb
As promised in my review of PR #109 - hope you like the suggestions, @brantr !
=> Butler description, help() examples

Visualization/AFW_Display_Demo.ipynb
@brantr @drphilmarshall I've added another subsection on displaying masked images. I'm happy to also make the change in nomenclature suggested in the review of #109, just let me know if you agree.
=> Adding masked image plotting

ImageProcessing/Re-RunHSC.ipynb, ImageProcessing/Re-RunHSC.sh
@jtmyles Here are some improvements arising from my review of your HSC re-run project (#86), see what you think. The consistent commenting in the script should enable snippets of it to be extracted throughout the notebook, and I made a start at cleaning up the environment variables in the notebook cells.
=> Script commenting, Pipeline Preview, HOME, DATADIR etc 

GettingStarted/GettingStarted.md
I verified that AnyConnect works on Linux and added some details about potentially needing `openconnect`.
=> Update to GettingStarted

GettingStarted/FindingDocs.ipynb, GettingStarted/GettingStarted.md
Turns out I had already added some notes to the Getting Started file, but I think the emphasis was a bit off - you're right that everyone should set up the package, just so they can use it.
=> Better emphasis on developing and using the stackclub package

Syllabus.md
Not yet ready for review! But here's where I'm addressing my own review comments in PR #125: 
I'll add more to-do's to the list above as I go, and then request a review from Alex when I'm done.
=> Iteration on the initial Course Syllabus

Basics/Exploring_A_Data_Repo.ipynb
Plus some other suggested improvements. What do you think, @rmorgan10 ?
=> Iteration on dataset exists problem

Basics/DataInventory.ipynb, stackclub/__init__.py, stackclub/taster.py
@rmorgan10 I had a go at transferring the data repo exploration code from our notebook into a `Taster` worker class: I'm using the Data Inventory notebook to demo it. See what you think - next job could be to make a skymap plot, I think. 
BTW, I suspect a bug but can't see what I've done wrong: the HSC dataset should have different datasets in the WIDE, DEEP and UDEEP repos, right? Right now I see this:
=> `Taster` class for packaged-up data repo exploration 

Basics/README.rst, Calibration/README.rst, Deblending/README.rst, GettingStarted/README.rst, GettingStarted/templates/template_README.rst, ImageProcessing/README.rst, Measurement/README.rst, SourceDetection/README.rst, Validation/README.rst, Visualization/README.rst, docs/_static/theme_overrides.css, docs/conf.py, docs/index.rst, docs/notebooks.rst, docs/stackclub.rst
Just to get started, I re-made the docs/index.rst file as a global Stack Club home page, and moved the `stackclub` package API docs to a separate RST file. Next up I'll try to bring in the notebooks. This is not ready for review yet - but I'll keep you posted, and log my progress on issue #164 in this PR thread.
=> Stack Club notebooks on RTD

Basics/afw_table_guided_tour.ipynb
problems were: 
*have to use 'calexp_photoCalib' instead of 'calexp_calib' as the data product to retrieve to get magnitudes
*have to use `photoCalib`.instFluxToMagnitude' now instead of 'getMagnitude'
=> v18 updates for introduction to afw table 

Basics/Calexp_guided_tour.ipynb
This pull request updates the Calexp Guided Tour for v18.1.0. It includes some work-in-progress made over the past year, that I had not gotten around to making into a pull request.
* Update the import of `Point2D` which causes builds to fail
* Show how to use `afwDisplay` to display the PSF (a request from LSST PCW 2018)
* Include a new section on using `VisitInfo` and `ExposureInfo`
The new notebook runs for me on lsst-lsp-stable with v18.1.0.
=> Update Calexp Guided Tour and add VisitInfo

Deblending/lsst_stack_deblender.ipynb
This PR addresses Issue #166 and includes minor modifications to `lsst_stack_deblender.ipynb` so that it runs with version `w_2019_06` of the stack. Changes were made in configuring the `SingleFrameMeasurementTask`, where the line `measureConfig.slots.instFlux = None` resulted in an attribute error:
```AttributeError: lsst.meas.base.baseMeasurement.SourceSlotConfig has no attribute instFlux```
and subsequently running `table = SourceCatalog.Table.make(schema)` resulted in:
```
NotFoundError: 
File "src/table/Schema.cc", line 226, in lsst::afw::table::SchemaItem<T> lsst::afw::table::detail::SchemaImpl::find(const string&) const [with T = double; std::string = std::basic_string<char>]
Field or subfield with name 'base_GaussianFlux_instFlux' not found with type 'D'. {0} …
```
=> Run deblending tutorial on current version of the stack

Basics/ButlerTutorial.ipynb
Minor text clarifications to `Basics/ButlerTutorial.ipynb`. Includes a sight addition to the discussion on selecting subsets of data, and explicitly notes that cutout images are returned as `ExposureF` objects.
=> Fixes incorrect object type name

GettingStarted/FindingDocs.ipynb, GettingStarted/ImportTricks.ipynb, stackclub/where_is.py
* Update `where_is` function
* Updates to FindingDocs.ipynb and ImportTricks.ipynb notebooks.
* Replace a missing gist url with a url to a matplotlib example
* Closes #234 
Note that ImportTricks.ipynb is pulling `where_is` from master, so it will fail until this PR is merged.
This PR is ready for review.
=> Updating stackclub doc finding

SourceDetection/LowSurfaceBrightness.ipynb
Updating the LowSurfaceBrightness notebook to run on v20. Removed dependency on Twinkles data and replaced with the HSC RC data set (`/datasets/hsc/repo/rerun/RC/v20_0_0_rc1/DM-25349`). 
This is work towards issue #236.
=> Update LowSurfaceBrightness for v20

Validation/DC2_refcat_loader_demo.ipynb
This notebook shows how to identify and load a reference catalog. 
Unlike refcat_loader_demo.ipynb this demo uses the DC2 dataset, and can be run on the IDF
I think this notebook could use a little more text before it is merged, comments/suggestions on the content are welcome
=> Adding in refcat demo that works on IDF
